name: Publish to npm
on:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '18.x'
                  registry-url: https://registry.npmjs.org
                  always-auth: true
            - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
            - run: npm ci
            - run: |
                  git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
                  git config --global user.name "Dora Militaru"
            - run: npm version ${{github.ref_name}} --allow-same-version
            - run: npm publish
